modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="beyondtheend"
version="1.0.0"
displayName="Beyond the End"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="aahbr, MCreator"

[[dependencies.beyondtheend]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




